import { MODES, DIFFICULTIES, DEFAULT_THEME } from './config.js';

export const DEFAULT_SETTINGS = {
  mode: MODES.PARAGRAPH,
  duration: 30,
  wordCount: 50,
  difficulty: DIFFICULTIES.MEDIUM,
  language: 'en',
  theme: DEFAULT_THEME,
  fontFamily: 'monospace',
  fontSize: 24,
  caretStyle: 'line',
  smoothCaret: true,
  soundEnabled: true,
  soundVolume: 0.5,
  typingVolume: 0.4,
  feedbackVolume: 0.7,
  uiVolume: 0.3,
  soundProfile: 'mechanical',
  reducedMotion: false,
  highContrast: false,
  colorBlindSafe: false,
  blindMode: false,
  stopOnError: false,
  freedom: true,
  confidence: false,
  easyMode: false,
  fairPlay: true,
  showKeyboard: false,
  layout: 'qwerty',
};
