/**
 * Extra snippets for the remaining languages (html, css, sql, json,
 * markdown, bash). Loaded by inject.cjs.
 */
module.exports = {
  html: [
    { id: 'html-form', name: 'Accessible Form', code: `<form class="login-card" method="POST" action="/login">\n  <label for="user-email">Email Address</label>\n  <input type="email" id="user-email" name="email" required autocomplete="email" />\n  <button type="submit" class="btn btn-primary">Sign In</button>\n</form>` },
    { id: 'html-semantic-layout', name: 'Semantic Page Layout', code: `<body>\n  <header>\n    <nav aria-label="Primary">\n      <a href="/">Home</a>\n      <a href="/about">About</a>\n    </nav>\n  </header>\n  <main>\n    <article>\n      <h1>Article Title</h1>\n      <p>Article content goes here.</p>\n    </article>\n  </main>\n  <footer>&copy; 2024 KeyFlow</footer>\n</body>` },
    { id: 'html-table', name: 'Data Table', code: `<table>\n  <caption>Recent Sessions</caption>\n  <thead>\n    <tr>\n      <th scope="col">Date</th>\n      <th scope="col">WPM</th>\n      <th scope="col">Accuracy</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>2024-01-15</td>\n      <td>95</td>\n      <td>98%</td>\n    </tr>\n  </tbody>\n</table>` },
    { id: 'html-dialog', name: 'Native Dialog Element', code: `<dialog id="confirm-dialog">\n  <h2>Confirm Action</h2>\n  <p>Are you sure you want to delete this session?</p>\n  <menu>\n    <button value="cancel">Cancel</button>\n    <button value="confirm" autofocus>Confirm</button>\n  </menu>\n</dialog>` },
    { id: 'html-article-blog', name: 'Blog Post with Metadata', code: `<article>\n  <header>\n    <h1>The Joy of Small Modules</h1>\n    <p>\n      <time datetime="2024-01-15">January 15, 2024</time>\n      &middot; 8 min read\n    </p>\n  </header>\n  <p>Programs are made of parts, and parts are made of parts...</p>\n  <footer>\n    <p>Tags: <a href="/t/architecture">architecture</a>, <a href="/t/modules">modules</a></p>\n  </footer>\n</article>` },
    { id: 'html-progress', name: 'Progress Bar with ARIA', code: `<div role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"\n     aria-label="Test progress" class="progress">\n  <div class="progress-fill" style="width: 65%"></div>\n  <span class="sr-only">65% complete</span>\n</div>` },
    { id: 'html-aria-tabs', name: 'ARIA Tabs', code: `<div role="tablist" aria-label="Settings tabs">\n  <button role="tab" id="tab-1" aria-selected="true" aria-controls="panel-1">\n    General\n  </button>\n  <button role="tab" id="tab-2" aria-selected="false" aria-controls="panel-2" tabindex="-1">\n    Privacy\n  </button>\n</div>\n<div role="tabpanel" id="panel-1" aria-labelledby="tab-1">General settings</div>\n<div role="tabpanel" id="panel-2" aria-labelledby="tab-2" hidden>Privacy settings</div>` },
    { id: 'html-figure', name: 'Figure With Caption', code: `<figure>\n  <img src="/images/wpm-chart.png" alt="WPM over time" width="600" height="300" />\n  <figcaption>Words per minute over the last 30 days</figcaption>\n</figure>` },
    { id: 'html-nav-breadcrumb', name: 'Breadcrumb Navigation', code: `<nav aria-label="Breadcrumb">\n  <ol>\n    <li><a href="/">Home</a></li>\n    <li><a href="/practice">Practice</a></li>\n    <li><a href="/practice/typing">Typing</a></li>\n    <li aria-current="page">Results</li>\n  </ol>\n</nav>` },
  ],

  css: [
    { id: 'css-grid', name: 'Grid Layout', code: `.grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n  gap: 1.5rem;\n  padding: 1.5rem;\n}\n\n.card {\n  background: rgba(255, 255, 255, 0.04);\n  border: 1px solid rgba(255, 255, 255, 0.08);\n  border-radius: 12px;\n  padding: 1.5rem;\n}` },
    { id: 'css-custom-properties', name: 'Themeable Custom Properties', code: `:root {\n  --color-bg: #0f0f12;\n  --color-text: #e2e2e2;\n  --space-unit: 8px;\n}\n\n[data-theme='light'] {\n  --color-bg: #ffffff;\n  --color-text: #111111;\n}\n\n.card {\n  background: var(--color-bg);\n  color: var(--color-text);\n  padding: calc(var(--space-unit) * 3);\n}` },
    { id: 'css-flexbox-nav', name: 'Responsive Flexbox Nav', code: `.nav {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  flex-wrap: wrap;\n  gap: 1rem;\n  padding: 1rem 2rem;\n}\n\n@media (max-width: 640px) {\n  .nav {\n    flex-direction: column;\n    align-items: flex-start;\n  }\n}` },
    { id: 'css-keyframes', name: 'Keyframe Animation', code: `@keyframes fadeSlideIn {\n  from {\n    opacity: 0;\n    transform: translateY(12px);\n  }\n  to {\n    opacity: 1;\n    transform: translateY(0);\n  }\n}\n\n.toast {\n  animation: fadeSlideIn 0.3s ease-out forwards;\n}` },
    { id: 'css-container-query', name: 'Container Query', code: `.card-wrapper {\n  container-type: inline-size;\n  container-name: card;\n}\n\n@container card (min-width: 400px) {\n  .card {\n    display: grid;\n    grid-template-columns: 1fr 2fr;\n  }\n}` },
    { id: 'css-houdini-paint', name: 'Custom Property Animation', code: `.progress {\n  --progress: 0%;\n  background: linear-gradient(to right, #3b82f6 var(--progress), #1f2937 var(--progress));\n  height: 8px;\n  border-radius: 4px;\n  transition: --progress 0.4s ease;\n  animation: fill 2s forwards;\n}\n\n@keyframes fill {\n  to { --progress: 100%; }\n}\n\n@property --progress {\n  syntax: '<percentage>';\n  initial-value: 0%;\n  inherits: false;\n}` },
    { id: 'css-logical-properties', name: 'Logical Properties', code: `.card {\n  margin-block: 1rem;\n  margin-inline: auto;\n  padding-block: 1.5rem;\n  padding-inline: 2rem;\n  border-start-start-radius: 0.75rem;\n  border-end-end-radius: 0.75rem;\n  max-inline-size: 60ch;\n}\n\n.dual {\n  display: flex;\n  flex-direction: row;\n}` },
    { id: 'css-cascade-layers', name: 'Cascade Layers', code: `@layer reset, base, components, utilities;\n\n@layer reset {\n  *, *::before, *::after {\n    margin: 0;\n    padding: 0;\n    box-sizing: border-box;\n  }\n}\n\n@layer base {\n  body {\n    font-family: system-ui, sans-serif;\n    line-height: 1.5;\n  }\n}\n\n@layer components {\n  .button {\n    padding: 0.5rem 1rem;\n    background: var(--color-primary, blue);\n    color: white;\n  }\n}` },
    { id: 'css-fluid-typography', name: 'Fluid Typography', code: `h1 {\n  font-size: clamp(1.5rem, 2vw + 1rem, 3rem);\n  line-height: 1.2;\n  font-weight: 700;\n}\n\nh2 {\n  font-size: clamp(1.25rem, 1.5vw + 0.75rem, 2rem);\n  line-height: 1.3;\n}\n\np {\n  font-size: clamp(1rem, 0.5vw + 0.875rem, 1.125rem);\n  line-height: 1.6;\n}` },
  ],

  sql: [
    { id: 'sql-window-funcs', name: 'Window Functions', code: `SELECT\n    user_id,\n    amount,\n    SUM(amount) OVER (PARTITION BY user_id ORDER BY created_at) AS running_total,\n    RANK() OVER (PARTITION BY user_id ORDER BY amount DESC) AS amount_rank\nFROM orders\nWHERE created_at >= NOW() - INTERVAL '30 days'\nORDER BY user_id, created_at DESC;` },
    { id: 'sql-cte', name: 'Common Table Expression', code: `WITH monthly_sales AS (\n    SELECT\n        DATE_TRUNC('month', created_at) AS month,\n        SUM(amount) AS total\n    FROM orders\n    GROUP BY 1\n),\nprevious_month AS (\n    SELECT total FROM monthly_sales ORDER BY month DESC LIMIT 1 OFFSET 1\n)\nSELECT\n    ms.month,\n    ms.total,\n    ms.total - pm.total AS change\nFROM monthly_sales ms\nCROSS JOIN previous_month pm\nORDER BY ms.month DESC;` },
    { id: 'sql-upsert', name: 'Upsert (ON CONFLICT)', code: `INSERT INTO user_settings (user_id, theme, sound_enabled)\nVALUES ($1, $2, $3)\nON CONFLICT (user_id)\nDO UPDATE SET\n    theme = EXCLUDED.theme,\n    sound_enabled = EXCLUDED.sound_enabled\nRETURNING updated_at;` },
    { id: 'sql-index-constraint', name: 'Index and Constraint', code: `CREATE TABLE sessions (\n    id SERIAL PRIMARY KEY,\n    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n    wpm INTEGER NOT NULL CHECK (wpm >= 0),\n    accuracy NUMERIC(4, 2) CHECK (accuracy BETWEEN 0 AND 100),\n    created_at TIMESTAMPTZ DEFAULT NOW()\n);\n\nCREATE INDEX idx_sessions_user_id ON sessions(user_id);\nCREATE INDEX idx_sessions_created_at ON sessions(created_at DESC);` },
    { id: 'sql-recursive-cte', name: 'Recursive CTE (Org Tree)', code: `WITH RECURSIVE org_tree AS (\n    SELECT id, name, manager_id, 1 AS depth\n    FROM employees\n    WHERE manager_id IS NULL\n    UNION ALL\n    SELECT e.id, e.name, e.manager_id, t.depth + 1\n    FROM employees e\n    JOIN org_tree t ON e.manager_id = t.id\n)\nSELECT id, name, depth\nFROM org_tree\nORDER BY depth, name;` },
    { id: 'sql-aggregates-having', name: 'GROUP BY with HAVING', code: `SELECT\n    user_id,\n    COUNT(*) AS session_count,\n    AVG(wpm) AS avg_wpm,\n    MAX(wpm) AS best_wpm,\n    MIN(accuracy) AS worst_accuracy\nFROM sessions\nWHERE created_at >= NOW() - INTERVAL '7 days'\nGROUP BY user_id\nHAVING COUNT(*) >= 3 AND AVG(wpm) > 50\nORDER BY avg_wpm DESC;` },
    { id: 'sql-json-ops', name: 'JSON Column Query', code: `SELECT\n    id,\n    metadata->>'name' AS name,\n    metadata->>'plan' AS plan,\n    (metadata->>'usage_minutes')::int AS usage_minutes\nFROM accounts\nWHERE metadata->>'plan' = 'pro'\n  AND (metadata->>'usage_minutes')::int > 1000\nORDER BY usage_minutes DESC;` },
    { id: 'sql-pagination', name: 'Cursor-Based Pagination', code: `SELECT id, title, created_at\nFROM articles\nWHERE (created_at, id) < ($1, $2)\nORDER BY created_at DESC, id DESC\nLIMIT 20;` },
    { id: 'sql-explain', name: 'EXPLAIN ANALYZE', code: `EXPLAIN ANALYZE\nSELECT u.id, u.name, COUNT(s.id) AS session_count\nFROM users u\nLEFT JOIN sessions s ON s.user_id = u.id\nWHERE u.created_at >= NOW() - INTERVAL '30 days'\nGROUP BY u.id\nORDER BY session_count DESC\nLIMIT 10;` },
    { id: 'sql-materialized-view', name: 'Materialized View', code: `CREATE MATERIALIZED VIEW daily_user_stats AS\nSELECT\n    user_id,\n    DATE(created_at) AS day,\n    COUNT(*) AS sessions,\n    AVG(wpm) AS avg_wpm,\n    MAX(wpm) AS best_wpm\nFROM sessions\nWHERE created_at >= NOW() - INTERVAL '90 days'\nGROUP BY user_id, DATE(created_at);\n\nCREATE UNIQUE INDEX idx_daily_user_stats\n  ON daily_user_stats(user_id, day);` },
  ],

  json: [
    { id: 'json-config', name: 'Application Config', code: `{\n  "app": {\n    "name": "KeyFlow",\n    "version": "1.0.0",\n    "locale": "en"\n  },\n  "server": {\n    "port": 8080,\n    "timeout": 30,\n    "cors": ["https://example.com"]\n  },\n  "features": {\n    "leaderboards": true,\n    "multiplayer": false,\n    "tournaments": true\n  }\n}` },
    { id: 'json-api-response', name: 'API Response Envelope', code: `{\n  "status": "success",\n  "data": {\n    "users": [\n      { "id": 1, "name": "Ada", "email": "ada@example.com\ },\\n      { \"id\": 2, \"name\": \"Grace\", \"email\": \"grace@example.com\" }\\n    ],\\n    \"pagination\": { \"page\": 1, \"per_page\": 20, \"total\": 42 }\\n  },\\n  \"meta\": {\\n    \"requestId\": \"a1b2c3\",\\n    \"timestamp\": \"2024-01-15T10:30:00Z\"\\n  }\\n}`},
    { id: 'json-package', name: 'Package Manifest', code: `{\n  "name": "@keyflow/typing-engine",\n  "version": "2.1.0",\n  "description": "Core typing engine for KeyFlow",\n  "main": "dist/index.js",\n  "types": "dist/index.d.ts",\n  "dependencies": {\n    "fuse.js": "^7.0.0"\n  },\n  "devDependencies": {\n    "typescript": "^5.4.0",\n    "vitest": "^1.6.0"\n  }\n}` },
    { id: 'json-typed-config', name: 'Typed Config Schema', code: `{\n  "$schema": "https://json-schema.org/draft/2020-12/schema",\n  "type": "object",\n  "title": "UserSettings",\n  "properties": {\n    "theme": {\n      "type": "string",\n      "enum": ["paper", "carbon", "dusk", "aurora", "sunset", "serif", "mono"],\n      "default": "paper"\n    },\n    "soundEnabled": { "type": "boolean", "default": true },\n    "soundVolume": { "type": "number", "minimum": 0, "maximum": 1, "default": 0.5 },\n    "language": { "type": "string", "default": "en\ }\\n  },\\n  \"required\": [\"theme\", \"language\"]\\n}`},
    { id: 'json-i18n', name: 'i18n Translation File', code: `{\n  "en": {\n    "app.title": "KeyFlow",\n    "nav.practice": "Practice",\n    "nav.developer": "Developer",\n    "action.start": "Start typing",\n    "message.complete": "Test complete!"\n  },\n  "fr": {\n    "app.title": "KeyFlow",\n    "nav.practice": "Pratique",\n    "nav.developer": "Développeur",\n    "action.start": "Commencer à taper",\n    "message.complete": "Test terminé !"\n  },\n  "de": {\n    "app.title": "KeyFlow",\n    "nav.practice": "Übung",\n    "nav.developer": "Entwickler",\n    "action.start": "Tippen starten",\n    "message.complete": "Test abgeschlossen!"\n  }\n}` },
    { id: 'json-tsconfig', name: 'TypeScript Config', code: `{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "strict": true,\n    "noUncheckedIndexedAccess": true,\n    "exactOptionalPropertyTypes": true,\n    "skipLibCheck": true,\n    "jsx": "preserve"\n  },\n  "include": ["src/**/*"],\n  "exclude": ["node_modules", "dist"]\n}` },
    { id: 'json-vite', name: 'Vite Config', code: `{\n  "name": "keyflow",\n  "private": true,\n  "type": "module",\n  "scripts": {\n    "dev": "vite",\n    "build": "vite build",\n    "preview": "vite preview",\n    "test": "vitest"\n  },\n  "dependencies": {\n    "firebase": "^12.0.0"\n  },\n  "devDependencies": {\n    "playwright": "^1.40.0",\n    "vite": "^6.0.0"\n  }\n}` },
    { id: 'json-eslint', name: 'ESLint Config', code: `{\n  "root": true,\n  "env": { "browser": true, "es2022": true },\n  "extends": [\n    "eslint:recommended",\n    "plugin:@typescript-eslint/recommended"\n  ],\n  "parser": "@typescript-eslint/parser",\n  "rules": {\n    "no-console": "warn",\n    "prefer-const": "error",\n    "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_\ }]\\n  }\\n}`},
    { id: 'json-lighthouse', name: 'Lighthouse Audit Config', code: `{\n  "ci": {\n    "collect": {\n      "url": ["http://localhost:8080/"],\n      "numberOfRuns": 3\n    },\n    "assert": {\n      "preset": "lighthouse:recommended",\n      "assertions": {\n        "categories:performance": ["warn", { "minScore": 0.9 }],\n        "categories:accessibility": ["error", { "minScore": 0.95 }],\n        "categories:best-practices": ["warn", { "minScore": 0.9 }],\n        "categories:seo": ["warn", { "minScore": 0.9 }]\n      }\n    }\n  }\n}` },
  ],

  markdown: [
    { id: 'md-readme', name: 'Open Source Readme', code: `# KeyFlow Typing Engine\n\nA fast, accessible typing engine for the modern web.\n\n## Features\n\n- **Real-time WPM and accuracy** - every keystroke updates the metrics.\n- **Multi-language support** - paragraphs in 10 languages: English, French, German, Italian, Portuguese, Swedish, Polish, Czech, Turkish, Romanian.\n- **Developer mode** - practice code in 16 programming languages with proper indentation and bracket tracking.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## License\n\nMIT. See [LICENSE](./LICENSE) for details.` },
    { id: 'md-changelog', name: 'Changelog Entry', code: `## [2.1.0] - 2024-01-15\n\n### Added\n- **Multilingual prose** - paragraphs in French, German, Italian, Portuguese, Swedish, Polish, Czech, Turkish, and Romanian, each with id, source, difficulty, category, language, and name fields.\n- **Named developer snippets** - every snippet in src/content/developer/languages.js has a human-readable name so the editor tab shows the program title.\n\n### Changed\n- Practice page now exposes a language selector inside the "More options" disclosure.\n- The dev-page tab filename is derived from the snippet name (snake_case + language extension).\n\n### Fixed\n- Caret coordinate system: spans and caret now share the same container.\n- Time mode actually has a timer - completion is wall-clock based.` },
    { id: 'md-api-docs', name: 'API Documentation Block', code: `## getText(mode, difficulty, options)\n\nRetrieves practice text for the given mode.\n\n### Parameters\n\n| Parameter    | Type     | Description                |\n|--------------|----------|----------------------------|\n| mode         | string   | One of the supported modes |\n| difficulty   | string   | easy, medium, hard, expert |\n| options      | object   | Mode-specific options      |\n\n### Returns\n\nA promise resolving to a string. The string length depends on the\nselected duration and difficulty.\n\n### Example\n\n\`\`\`js\nconst text = await getText("paragraph", "medium", { duration: 30 });\nconsole.log(text.length);\n\`\`\`` },
    { id: 'md-feature-grid', name: 'Feature Grid Table', code: `| Feature              | Status   | Notes                  |\n|----------------------|----------|------------------------|\n| Multilingual prose   | Stable   | 9 non-English languages  |\n| Live WPM             | Stable   | Updated per keystroke  |\n| Replay               | Beta     | Storage-bounded        |\n| Cloud sync           | Planned  | Roadmap Q2             |` },
    { id: 'md-contributing', name: 'Contributing Guide', code: `# Contributing\n\nThanks for your interest in making KeyFlow better. This document\nexplains how to set up a development environment and submit changes.\n\n## Development Setup\n\n1. Fork and clone the repository.\n2. Install dependencies with npm install.\n3. Run the dev server with npm run dev.\n4. Run the test suite with npm test.\n\n## Pull Request Process\n\n1. Make your changes in a feature branch.\n2. Add tests for any new behaviour.\n3. Ensure the full test suite still passes.\n4. Submit a pull request describing your change.` },
    { id: 'md-install-section', name: 'Install Section', code: `## Installation\n\n\`\`\`bash\n# Clone the repository\ngit clone https://github.com/keyflow/keyflow.git\ncd keyflow\n\n# Install dependencies\nnpm install\n\n# Start the dev server\nnpm run dev\n\`\`\`\n\nOpen http://localhost:5173 to view it in your browser.` },
    { id: 'md-troubleshooting', name: 'Troubleshooting Section', code: `## Troubleshooting\n\n### The dev server won\'t start\n\nMake sure you are using Node 20 or later. Earlier versions are not\nsupported.\n\n\`\`\`bash\nnode --version\n\`\`\`\n\nIf the version is correct but the server still fails, try removing\nnode_modules and reinstalling:\n\n\`\`\`bash\nrm -rf node_modules package-lock.json\nnpm install\n\`\`\`\n\n### Tests fail randomly\n\nRun them with --run flag for sequential execution:\n\n\`\`\`bash\nnpm test -- --run\n\`\`\`` },
    { id: 'md-license', name: 'License Block', code: `## License\n\nMIT License\n\nCopyright (c) 2024 KeyFlow Contributors\n\nPermission is hereby granted, free of charge, to any person obtaining\na copy of this software and associated documentation files (the\n"Software"), to deal in the Software without restriction, including\nwithout limitation the rights to use, copy, modify, merge, publish,\ndistribute, sublicense, and/or sell copies of the Software, and to\npermit persons to whom the Software is furnished to do so, subject\nto the following conditions:\n\nThe above copyright notice and this permission notice shall be\nincluded in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.` },
    { id: 'md-architecture', name: 'Architecture Diagram (ASCII)', code: `## Architecture\n\n\`\`\`\n                  +----------------+\n                  |  Keyboard      |\n                  +-------+--------+\n                          |\n                          v\n                  +-------+--------+\n                  |  InputEngine    |  (normalises events)\n                  +-------+--------+\n                          |\n                          v\n                  +-------+--------+\n                  |  Session Model  |  (source of truth)\n                  +-------+--------+\n                          |\n        +-----------------+------------------+\n        |                 |                  |\n        v                 v                  v\n   +--------+      +------------+     +-----------+\n   | Timer  |      |  Renderer  |     |  Stats    |\n   +--------+      +------------+     +-----------+\n\`\`\`` },
    { id: 'md-roadmap', name: 'Roadmap Table', code: `## Roadmap\n\n| Quarter | Milestone                          |\n|---------|-------------------------------------|\n| Q1 2024 | Multilingual prose support         |\n| Q2 2024 | Adaptive weak-key training         |\n| Q3 2024 | Cloud sync & leaderboards          |\n| Q4 2024 | Public benchmark & methodology    |\n\nHave a suggestion? Open an issue or join the discussion board.` },
  ],

  bash: [
    { id: 'bash-deploy', name: 'CI/CD Build Pipeline', code: `#!/usr/bin/env bash\nset -euo pipefail\n\necho "==> Running production build..."\nnpm run build\n\necho "==> Deploying artifacts..."\nrsync -avz --delete dist/ deploy@keyflow.app:/var/www/html/\necho "==> Deployment successful!"` },
    { id: 'bash-backup-script', name: 'Database Backup Script', code: `#!/usr/bin/env bash\nset -euo pipefail\n\nTIMESTAMP=$(date +%Y%m%d-%H%M%S)\nBACKUP_DIR="/var/backups/keyflow"\nmkdir -p "$BACKUP_DIR"\n\npg_dump keyflow_production | gzip > "$BACKUP_DIR/keyflow-$TIMESTAMP.sql.gz"\n\n# Keep only the last 7 days of backups\nfind "$BACKUP_DIR" -name "*.sql.gz" -mtime +7 -delete\n\necho "Backup saved to $BACKUP_DIR/keyflow-$TIMESTAMP.sql.gz"` },
    { id: 'bash-loop-retry', name: 'Retry Loop with Backoff', code: `#!/usr/bin/env bash\n\nretry() {\n    local attempts=0\n    local max_attempts=5\n    until "$@"; do\n        attempts=$((attempts + 1))\n        if [ "$attempts" -ge "$max_attempts" ]; then\n            echo "Command failed after $max_attempts attempts" >&2\n            return 1\n        fi\n        sleep $((attempts * 2))\n    done\n}\n\nretry curl --fail --silent https://api.example.com/health` },
    { id: 'bash-arg-parse', name: 'Argument Parsing', code: `#!/usr/bin/env bash\n\nusage() {\n    echo "Usage: $0 [-v] [-f FILE] NAME"\n    exit 1\n}\n\nVERBOSE=false\nFILE=""\n\nwhile [[ $# -gt 0 ]]; do\n    case "$1" in\n        -v|--verbose)\n            VERBOSE=true\n            shift\n            ;;\n        -f|--file)\n            FILE="$2"\n            shift 2\n            ;;\n        -h|--help)\n            usage\n            ;;\n        *)\n            NAME="$1"\n            shift\n            ;;\n    esac\ndone\n\n[[ -z "$NAME" ]] && usage\n\n$VERBOSE && echo "Verbose mode enabled"\necho "Name: $NAME, File: $FILE"` },
    { id: 'bash-deps-check', name: 'Check Missing Dependencies', code: `#!/usr/bin/env bash\n\ndeclare -a DEPS=("node" "npm" "git" "python3" "docker")\n\nmissing=()\nfor dep in "\${DEPS[@]}"; do\n    if ! command -v "$dep" >/dev/null 2>&1; then\n        missing+=("$dep")\n    fi\ndone\n\nif [ \${#missing[@]} -gt 0 ]; then\n    echo "Missing: \${missing[*]}"\n    echo "Install them before running this script."\n    exit 1\nfi\n\necho "All dependencies are present."` },
    { id: 'bash-log-rotation', name: 'Log Rotation Script', code: `#!/usr/bin/env bash\n\nLOG_DIR="/var/log/keyflow"\nARCHIVE_DIR="/var/log/keyflow/archive"\nMAX_SIZE="100M"\n\nmkdir -p "$ARCHIVE_DIR"\n\nfor log in "$LOG_DIR"/*.log; do\n    [ -f "$log" ] || continue\n    size=$(stat -c%s "$log")\n    if [ "$size" -gt 100000000 ]; then\n        ts=$(date +%Y%m%d-%H%M%S)\n        base=$(basename "$log" .log)\n        gzip "$log"\n        mv "\${log}.gz" "$ARCHIVE_DIR/\${base}-\${ts}.log.gz"\n        touch "$log"\n        echo "Rotated $log"\n    fi\ndone` },
    { id: 'bash-file-watcher', name: 'File Watcher Loop', code: `#!/usr/bin/env bash\n\nWATCH_DIR="\${1:-./src}"\nEXT="\${2:-js}"\n\necho "Watching $WATCH_DIR for *.$EXT changes..."\n\nlast_hash=""\nwhile true; do\n    current_hash=$(find "$WATCH_DIR" -name "*.$EXT" -type f -exec md5sum {} \\; 2>/dev/null | sort | md5sum | cut -d' ' -f1)\n    if [ "$current_hash" != "$last_hash" ] && [ -n "$last_hash" ]; then\n        echo "Change detected at $(date +%H:%M:%S)"\n    fi\n    last_hash="$current_hash"\n    sleep 2\ndone` },
    { id: 'bash-system-info', name: 'System Info Reporter', code: `#!/bin/bash\n\necho "=== System Information ==="\necho "Hostname: $(hostname)"\necho "Kernel:   $(uname -r)"\necho "OS:       $(uname -s)"\necho "Uptime:   $(uptime -p 2>/dev/null || uptime)"\necho\n\necho "=== Resources ==="\necho "Memory:   $(free -h | awk '/Mem:/ {print $3 " / " $2}')"\necho "Disk:     $(df -h / | awk 'NR==2 {print $3 " / " $2 " (" $5 ")\`}')\"\\necho \"Load:     $(uptime | awk -F'load average:' '{print $2}')\"\\necho\\n\\necho \"=== Network ===\"\\nip -4 addr show 2>/dev/null | awk '/inet / && !/127.0.0.1/ {print \"  \" $2}' || echo \"  (no info)`},
    { id: 'bash-text-processing', name: 'Log Analyzer', code: `#!/bin/bash\n\nLOG="\${1:-/var/log/syslog}"\nTOP_N=10\n\necho "Top $TOP_N error patterns in $LOG:"\ngrep -oE '[A-Z][a-zA-Z]+Error' "$LOG" 2>/dev/null |\n    sort | uniq -c | sort -rn | head -n "$TOP_N" |\n    awk '{printf "  %5d  %s\\n", $1, $2}'\n\necho\necho "Status code distribution:"\nawk '/HTTP\\/1.1./ {for(i=1;i<=NF;i++) if($i ~ /^[0-9]{3}$/) print $i}' "$LOG" 2>/dev/null |\n    sort | uniq -c | sort -rn | head -n 5` },
    { id: 'bash-ssh-deploy', name: 'SSH-Based Deployment', code: `#!/usr/bin/env bash\nset -euo pipefail\n\nHOST="\${1:-deploy@keyflow.app}"\nREMOTE_DIR="/var/www/keyflow"\n\necho "==> Building locally..."\nnpm run build\n\necho "==> Syncing to $HOST..."\nrsync -avz --delete \\\n    --exclude 'node_modules' \\\n    --exclude '.git' \\\n    --exclude '.env' \\\n    dist/ "\${HOST}:\${REMOTE_DIR}/"\n\necho "==> Reloading remote service..."\nssh "\${HOST}" 'sudo systemctl reload keyflow.service'\n\necho "==> Deployment complete!"` },
  ],
};
